[package]
name = "memory_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
nix = "0.25.0"
serde_json = "1.0.85"
simple-websockets = "0.1.4"
