[package]
name = "rosu-memory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-tungstenite = "0.23.0"
cfg-if = "1.0.0"
crossbeam-channel = "0.5.8"
futures-util = "0.3.28"
miniserde = "0.1.34"
paste = "1.0.14"
smol = "1.3.0"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.25.0",  default-features = false,  features = ["uio", "process", "feature"] }

[target.'cfg(windows)'.dependencies]
windows = {version = "0.48", features = ["Win32_Foundation", "Win32_System_Diagnostics_ToolHelp", "Win32_System_Threading", "Win32_System_Memory", "Win32_System_Diagnostics_Debug", "Win32_System_ProcessStatus"] }

[profile.release]
lto = "thin"
codegen-units = 1
strip = "debuginfo"

[dev-dependencies]
rand = "0.8.5"

