[package]
name = "memory_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"

[target.'cfg(linux)'.dependencies]
nix = { version = "0.25.0",  default-features = false,  features = ["uio", "process", "feature"] }

[dependencies.windows]
version = "0.48"
features = [
    "Win32_Foundation",
	"Win32_System_Diagnostics_ToolHelp",
	"Win32_System_Threading",
	"Win32_System_Memory",
	"Win32_System_Diagnostics_Debug",
	"Win32_System_ProcessStatus"
]

[profile.release]
lto = "thin"
codegen-units = 1
strip = "debuginfo"

