[package]
name = "memory_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
nix = { version = "0.25.0",  default-features = false,  features = ["uio", "process", "feature"] }

[profile.release]
lto = "thin"
codegen-units = 1
strip = "debuginfo"

