[package]
name = "rosu-memory"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
clap = { version = "4.4.6", features = ["derive", "env"] }
eyre = "0.6.8"
futures-lite = "2.0.1"
paste = "1.0.14"
rosu-pp = "0.9.5"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
serde_repr = "0.1.16"
tide = { version = "0.16.0", default-features = false, features = ["h1-server"] }
tide-websockets = "0.4.0"
tracy-client = { version = "0.16.4", default-features = false }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.25.0",  default-features = false,  features = ["uio", "process", "feature"] }

[target.'cfg(windows)'.dependencies]
windows = {version = "0.48", features = ["Win32_Foundation", "Win32_System_Diagnostics_ToolHelp", "Win32_System_Threading", "Win32_System_Memory", "Win32_System_Diagnostics_Debug", "Win32_System_ProcessStatus"] }

[features]
tracy-profile = ["tracy-client/default"]

[profile.release]
opt-level = "s"
lto = "thin"
codegen-units = 1
strip = "debuginfo"

[profile.release.package."*"]
codegen-units = 1
opt-level = "s"
strip = "debuginfo"

[dev-dependencies]
rand = "0.8.5"
